source 'https://rubygems.org'
gem 'html-proofer'
gem 'i18n'
gem 'jekyll', '3.2.1'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'jekyll-sass-converter'
gem 'json'
gem 'sass'
gem 'stringex'
gem 'therubyracer'
