source 'https://rubygems.org'
gem 'i18n'
gem 'kramdown', '1.5.0'
gem 'jekyll', '2.4.0'
gem 'liquid', '2.6.2'
gem 'html-proofer'
gem 'jekyll-sass-converter'
gem 'sass'
gem 'redcarpet', '3.3.2'
gem 'therubyracer'
